---
name: Frontend Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-frontend:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: './frontend/package-lock.json'
          # node-version: ${{ matrix.node-version }}
          cache: 'npm'
    
      - run: cd frontend && npm install 
      - run: cd frontend && npm run test
